name: ecodsa_app
description: ECODSA

version: 0.0.1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+2
  simple_auth: ^2.0.5
  hive_flutter: ^0.2.1
  flutter_bloc: ^0.21.0
  equatable: ^0.6.1
  hydrated_bloc: ^0.6.0
  json_annotation: ^3.0.0

  carousel_slider: ^1.3.1
  smooth_star_rating: ^1.0.3
  font_awesome_flutter: ^8.5.0

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.7.1
  json_serializable: ^3.2.3

flutter:
  uses-material-design: true

  assets:
    - assets/img/

  fonts:
    - family: Mosk
      fonts:
        - asset: assets/fonts/Mosk-Thin.ttf
          weight: 100
        - asset: assets/fonts/Mosk-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Mosk-Light.ttf
          weight: 300
        - asset: assets/fonts/Mosk-Regular.ttf
          weight: 400
        - asset: assets/fonts/Mosk-Medium.ttf
          weight: 500
        - asset: assets/fonts/Mosk-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Mosk-Bold.ttf
          weight: 700
        - asset: assets/fonts/Mosk-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Mosk-Black.ttf
          weight: 900
